# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Foresight: Collect workflow telemetry'
        uses: runforesight/foresight-workflow-kit-action@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run linters
        run: tox run -e lint

  integration-test-lxd-database:
    name: Integration tests for mysql-bundle (lxd)
    needs:
      - lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 'Foresight: Collect workflow telemetry'
        uses: runforesight/foresight-workflow-kit-action@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
      - name: Run integration bundle test
        run: tox run -e integration --junit-xml=pytest_report.xml
      - name: 'Foresight: Collect test results'
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ success() || failure() }}
        with:
          test_framework: PYTEST
          test_format: JUNIT
          test_path: pytest_report.xml
