name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:
  integration-test:
    uses: ./.github/workflows/ci.yaml

  publish-bundle:
    name: Publish bundle
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - integration-test
    env:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
    steps:
      - name: 'Foresight: Collect workflow telemetry'
        uses: runforesight/foresight-workflow-kit-action@v1
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: sudo snap install charmcraft --classic
      - name: Pack and publish bundle
        run: |
          make release
